INSERT INTO tbl_waypoint (position, name, act) VALUES (0, 'Rogue Encampment', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (1, 'Cold Plains', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (2, 'Stony Field', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (3, 'Dark Wood', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (4, 'Black Marsh', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (5, 'Outer Cloister', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (6, 'Jail Level 1', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (7, 'Inner Cloister', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (8, 'Catacombs Level 2', 1);
INSERT INTO tbl_waypoint (position, name, act) VALUES (9, 'Lut Gholein', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (10, 'Sewers Level 2', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (11, 'Dry Hills', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (12, 'Halls of the Dead Level 2', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (13, 'Far Oasis', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (14, 'Lost City', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (15, 'Palace Cellar Level 1', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (16, 'Arcane Sanctuary', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (17, 'Canyon of the Magi', 2);
INSERT INTO tbl_waypoint (position, name, act) VALUES (18, 'Kurast Docktown', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (19, 'Spider Forest', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (20, 'Great Marsh', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (21, 'Flayer Jungle', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (22, 'Lower Kurast', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (23, 'Kurast Bazaar', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (24, 'Upper Kurast', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (25, 'Travincal', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (26, 'Durance of Hate Level 2', 3);
INSERT INTO tbl_waypoint (position, name, act) VALUES (27, 'The Pandemonium Fortress', 4);
INSERT INTO tbl_waypoint (position, name, act) VALUES (28, 'City of the Damned', 4);
INSERT INTO tbl_waypoint (position, name, act) VALUES (29, 'River of Flame', 4);
INSERT INTO tbl_waypoint (position, name, act) VALUES (30, 'Harrogath', 5);
INSERT INTO tbl_waypoint (position, name, act) VALUES (31, 'Figid Highlands', 5);
INSERT INTO tbl_waypoint (position, name, act) VALUES (32, 'Arreat Plateau', 5);
INSERT INTO tbl_waypoint (position, name, act) VALUES (33, 'Crystalline Passage', 5);
INSERT INTO tbl_waypoint (position, name, act) VALUES (34, 'Glacial Trail', 5);
INSERT INTO tbl_waypoint (position, name, act) VALUES (35, 'Halls of Pain', 5);
INSERT INTO tbl_waypoint (position, name, act) VALUES (36, 'Frozen Tundra', 5);
INSERT INTO tbl_waypoint (position, name, act) VALUES (37, 'The Ancient''s Way', 5);
INSERT INTO tbl_waypoint (position, name, act) VALUES (38, 'Worldstone Keep Level 2', 5);