INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (0, 'Bow and Crossbow Skills', 1);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (0, 'Passive and Magic Skills', 2);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (0, 'Javelin and Spear Skills', 3);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (1, 'Fire Spells', 1);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (1, 'Lighting Spells', 2);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (1, 'Cold Spells', 3);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (2, 'Curses', 1);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (2, 'Poison and Bone Spells', 2);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (2, 'Summoning Spells', 3);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (3, 'Combat Skills', 1);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (3, 'Offensive Auras', 2);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (3, 'Defencive Auras', 3);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (4, 'Combat Skills', 1);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (4, 'Combat Masteries', 2);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (4, 'Warcries', 3);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (5, 'Summoning', 1);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (5, 'Shape Shifting', 2);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (5, 'Elemental', 3);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (6, 'Traps', 1);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (6, 'Shadow Disciplines', 2);
INSERT INTO tbl_skill_page (class_id, name, page_order) VALUES (6, 'Martial Arts', 3);