DROP TABLE IF EXISTS tbl_class;
DROP TABLE IF EXISTS tbl_skill;
DROP TABLE IF EXISTS tbl_title;
DROP TABLE IF EXISTS tbl_skill_page;
DROP TABLE IF EXISTS tbl_attribute;
DROP TABLE IF EXISTS tbl_waypoint;
DROP TABLE IF EXISTS tbl_level;
DROP TABLE IF EXISTS tbl_quest;