INSERT INTO tbl_attribute (id, name, length) VALUES (0, 'Strength', 10);
INSERT INTO tbl_attribute (id, name, length) VALUES (1, 'Energy', 10);
INSERT INTO tbl_attribute (id, name, length) VALUES (2, 'Dexterity', 10);
INSERT INTO tbl_attribute (id, name, length) VALUES (3, 'Vitality', 10);
INSERT INTO tbl_attribute (id, name, length) VALUES (4, 'Stat points', 10);
INSERT INTO tbl_attribute (id, name, length) VALUES (5, 'Skill points', 8);
INSERT INTO tbl_attribute (id, name, length) VALUES (6, 'Hit point', 21);
INSERT INTO tbl_attribute (id, name, length) VALUES (7, 'Max hit points', 21);
INSERT INTO tbl_attribute (id, name, length) VALUES (8, 'Mana points', 21);
INSERT INTO tbl_attribute (id, name, length) VALUES (9, 'Max mana points', 21);
INSERT INTO tbl_attribute (id, name, length) VALUES (10, 'Stamina points', 21);
INSERT INTO tbl_attribute (id, name, length) VALUES (11, 'Max stamina points', 21);
INSERT INTO tbl_attribute (id, name, length) VALUES (12, 'Level', 7);
INSERT INTO tbl_attribute (id, name, length) VALUES (13, 'Experience', 32);
INSERT INTO tbl_attribute (id, name, length) VALUES (14, 'Gold', 25);
INSERT INTO tbl_attribute (id, name, length) VALUES (15, 'Gold in stash', 25);