INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Magic Arrow', 0, 1, 1, 2, '/icons/skills/amazon/0.png', 1);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fire Arrow', 0, 1, 1, 3, '/icons/skills/amazon/2.png', 2);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Inner Sight', 0, 2, 1, 1, '/icons/skills/amazon/4.png', 3);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Critical Strike', 0, 2, 1, 3, '/icons/skills/amazon/6.png', 4);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Jab', 0, 3, 1, 1, '/icons/skills/amazon/8.png', 5);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Cold Arrow', 0, 1, 2, 1, '/icons/skills/amazon/10.png', 6);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Multiple Shot', 0, 1, 2, 2, '/icons/skills/amazon/12.png', 7);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Dodge', 0, 2, 2, 2, '/icons/skills/amazon/14.png', 8);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Power Strike', 0, 3, 2, 2, '/icons/skills/amazon/16.png', 9);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Poison Javelin', 0, 3, 2, 3, '/icons/skills/amazon/18.png', 10);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Exploding Arrow', 0, 1, 3, 3, '/icons/skills/amazon/20.png', 11);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Slow Missiles', 0, 2, 3, 1, '/icons/skills/amazon/22.png', 12);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Avoid', 0, 2, 3, 2, '/icons/skills/amazon/24.png', 13);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Impale', 0, 3, 3, 1, '/icons/skills/amazon/26.png', 14);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Lightning Bolt', 0, 3, 3, 3, '/icons/skills/amazon/28.png', 15);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Ice Arrow', 0, 1, 4, 1, '/icons/skills/amazon/30.png', 16);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Guided Arrow', 0, 1, 4, 2, '/icons/skills/amazon/32.png', 17);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Penetrate', 0, 2, 4, 3, '/icons/skills/amazon/34.png', 18);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Charged Strike', 0, 3, 4, 2, '/icons/skills/amazon/36.png', 19);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Plague Javelin', 0, 3, 4, 3, '/icons/skills/amazon/38.png', 20);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Strafe', 0, 1, 5, 2, '/icons/skills/amazon/40.png', 21);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Immolation Arrow', 0, 1, 5, 3, '/icons/skills/amazon/42.png', 22);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Dopplezon', 0, 2, 5, 1, '/icons/skills/amazon/44.png', 23);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Evade', 0, 2, 5, 2, '/icons/skills/amazon/46.png', 24);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fend', 0, 3, 5, 1, '/icons/skills/amazon/48.png', 25);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Freezing Arrow', 0, 1, 6, 1, '/icons/skills/amazon/50.png', 26);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Valkyrie', 0, 2, 6, 1, '/icons/skills/amazon/52.png', 27);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Pierce', 0, 2, 6, 3, '/icons/skills/amazon/54.png', 28);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Lightning Strike', 0, 3, 6, 2, '/icons/skills/amazon/56.png', 29);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Lightning Fury', 0, 3, 6, 3, '/icons/skills/amazon/58.png', 30);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fire Bolt', 1, 1, 1, 2, '/icons/skills/sorceress/0.png', 1);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Warmth', 1, 1, 1, 3, '/icons/skills/sorceress/2.png', 2);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Charged Bolt', 1, 2, 1, 2, '/icons/skills/sorceress/4.png', 3);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Ice Bolt', 1, 3, 1, 2, '/icons/skills/sorceress/6.png', 4);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Frozen Armor', 1, 3, 1, 3, '/icons/skills/sorceress/8.png', 5);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Inferno', 1, 1, 2, 1, '/icons/skills/sorceress/10.png', 6);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Static Field', 1, 2, 2, 1, '/icons/skills/sorceress/12.png', 7);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Telekinesis', 1, 2, 2, 3, '/icons/skills/sorceress/14.png', 8);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Frost Nova', 1, 3, 2, 1, '/icons/skills/sorceress/16.png', 9);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Ice Blast', 1, 3, 2, 2, '/icons/skills/sorceress/18.png', 10);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Blaze', 1, 1, 3, 1, '/icons/skills/sorceress/20.png', 11);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fire Ball', 1, 1, 3, 2, '/icons/skills/sorceress/22.png', 12);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Nova', 1, 2, 3, 1, '/icons/skills/sorceress/24.png', 13);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Lightning', 1, 2, 3, 2, '/icons/skills/sorceress/26.png', 14);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Shiver Armor', 1, 3, 3, 3, '/icons/skills/sorceress/28.png', 15);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fire Wall', 1, 1, 4, 1, '/icons/skills/sorceress/30.png', 16);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Enchant', 1, 1, 4, 3, '/icons/skills/sorceress/32.png', 17);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Chain Lightning', 1, 2, 4, 2, '/icons/skills/sorceress/34.png', 18);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Teleport', 1, 2, 4, 3, '/icons/skills/sorceress/36.png', 19);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Glacial Spike', 1, 3, 4, 2, '/icons/skills/sorceress/38.png', 20);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Meteor', 1, 1, 5, 2, '/icons/skills/sorceress/40.png', 21);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Thunder Storm', 1, 2, 5, 1, '/icons/skills/sorceress/42.png', 22);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Energy Shield', 1, 2, 5, 3, '/icons/skills/sorceress/44.png', 23);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Blizzard', 1, 3, 5, 1, '/icons/skills/sorceress/46.png', 24);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Chilling Armor', 1, 3, 5, 3, '/icons/skills/sorceress/48.png', 25);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fire Mastery', 1, 1, 6, 2, '/icons/skills/sorceress/50.png', 26);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Hydra', 1, 1, 6, 3, '/icons/skills/sorceress/52.png', 27);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Lightning Mastery', 1, 2, 6, 2, '/icons/skills/sorceress/54.png', 28);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Frozen Orb', 1, 3, 6, 1, '/icons/skills/sorceress/56.png', 29);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Cold Mastery', 1, 3, 6, 2, '/icons/skills/sorceress/58.png', 30);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Amplify Damage', 2, 1, 1, 2, '/icons/skills/necromancer/0.png', 1);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Teeth', 2, 2, 1, 2, '/icons/skills/necromancer/2.png', 2);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Bone Armor', 2, 2, 1, 3, '/icons/skills/necromancer/4.png', 3);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Skeleton Mastery', 2, 3, 1, 1, '/icons/skills/necromancer/6.png', 4);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Raise Skeleton', 2, 3, 1, 3, '/icons/skills/necromancer/8.png', 5);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Dim Vision', 2, 1, 2, 1, '/icons/skills/necromancer/10.png', 6);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Weaken', 2, 1, 2, 3, '/icons/skills/necromancer/12.png', 7);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Poison Dagger', 2, 2, 2, 1, '/icons/skills/necromancer/14.png', 8);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Corpse Explosion', 2, 2, 2, 2, '/icons/skills/necromancer/16.png', 9);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Clay Golem', 2, 3, 2, 2, '/icons/skills/necromancer/18.png', 10);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Iron Maiden', 2, 1, 3, 2, '/icons/skills/necromancer/20.png', 11);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Terror', 2, 1, 3, 3, '/icons/skills/necromancer/22.png', 12);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Bone Wall', 2, 2, 3, 3, '/icons/skills/necromancer/24.png', 13);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Golem Mastery', 2, 3, 3, 1, '/icons/skills/necromancer/26.png', 14);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Raise Skeletal Mage', 2, 3, 3, 3, '/icons/skills/necromancer/28.png', 15);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Confuse', 2, 1, 4, 1, '/icons/skills/necromancer/30.png', 16);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Life Tap', 2, 1, 4, 2, '/icons/skills/necromancer/32.png', 17);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Poison Explosion', 2, 2, 4, 1, '/icons/skills/necromancer/34.png', 18);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Bone Spear', 2, 2, 4, 2, '/icons/skills/necromancer/36.png', 19);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('BloodGolem', 2, 3, 4, 2, '/icons/skills/necromancer/38.png', 20);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Attract', 2, 1, 5, 1, '/icons/skills/necromancer/40.png', 21);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Decrepify', 2, 1, 5, 3, '/icons/skills/necromancer/42.png', 22);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Bone Prison', 2, 2, 5, 3, '/icons/skills/necromancer/44.png', 23);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Summon Resist', 2, 3, 5, 1, '/icons/skills/necromancer/46.png', 24);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('IronGolem', 2, 3, 5, 2, '/icons/skills/necromancer/48.png', 25);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Lower Resist', 2, 1, 6, 2, '/icons/skills/necromancer/50.png', 26);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Poison Nova', 2, 2, 6, 1, '/icons/skills/necromancer/52.png', 27);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Bone Spirit', 2, 2, 6, 2, '/icons/skills/necromancer/54.png', 28);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('FireGolem', 2, 3, 6, 2, '/icons/skills/necromancer/56.png', 29);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Revive', 2, 3, 6, 3, '/icons/skills/necromancer/58.png', 30);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Sacrifice', 3, 1, 1, 1, '/icons/skills/paladin/0.png', 1);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Smite', 3, 1, 1, 3, '/icons/skills/paladin/2.png', 2);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Might', 3, 2, 1, 1, '/icons/skills/paladin/4.png', 3);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Prayer', 3, 3, 1, 1, '/icons/skills/paladin/6.png', 4);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Resist Fire', 3, 3, 1, 3, '/icons/skills/paladin/8.png', 5);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Holy Bolt', 3, 1, 2, 2, '/icons/skills/paladin/10.png', 6);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Holy Fire', 3, 2, 2, 2, '/icons/skills/paladin/12.png', 7);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Thorns', 3, 2, 2, 3, '/icons/skills/paladin/14.png', 8);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Defiance', 3, 3, 2, 2, '/icons/skills/paladin/16.png', 9);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Resist Cold', 3, 3, 2, 3, '/icons/skills/paladin/18.png', 10);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Zeal', 3, 1, 3, 1, '/icons/skills/paladin/20.png', 11);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Charge', 3, 1, 3, 3, '/icons/skills/paladin/22.png', 12);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Blessed Aim', 3, 2, 3, 1, '/icons/skills/paladin/24.png', 13);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Cleansing', 3, 3, 3, 1, '/icons/skills/paladin/38.png', 14);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Resist Lightning', 3, 3, 3, 3, '/icons/skills/paladin/28.png', 15);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Vengeance', 3, 1, 4, 1, '/icons/skills/paladin/40.png', 16);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Blessed Hammer', 3, 1, 4, 2, '/icons/skills/paladin/32.png', 17);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Concentration', 3, 2, 4, 1, '/icons/skills/paladin/34.png', 18);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Holy Freeze', 3, 2, 4, 2, '/icons/skills/paladin/36.png', 19);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Vigor', 3, 3, 4, 2, '/icons/skills/paladin/26.png', 20);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Conversion', 3, 1, 5, 1, '/icons/skills/paladin/30.png', 21);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Holy Shield', 3, 1, 5, 3, '/icons/skills/paladin/42.png', 22);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Holy Shock', 3, 2, 5, 2, '/icons/skills/paladin/44.png', 23);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Sanctuary', 3, 2, 5, 3, '/icons/skills/paladin/46.png', 24);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Meditation', 3, 3, 5, 1, '/icons/skills/paladin/48.png', 25);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fist of the Heavens', 3, 1, 6, 2, '/icons/skills/paladin/50.png', 26);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fanaticism', 3, 2, 6, 1, '/icons/skills/paladin/52.png', 27);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Conviction', 3, 2, 6, 3, '/icons/skills/paladin/56.png', 28);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Redemption', 3, 3, 6, 2, '/icons/skills/paladin/54.png', 29);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Salvation', 3, 3, 6, 3, '/icons/skills/paladin/58.png', 30);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Bash', 4, 1, 1, 2, '/icons/skills/barbarian/0.png', 1);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Sword Mastery', 4, 2, 1, 1, '/icons/skills/barbarian/2.png', 2);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Axe Mastery', 4, 2, 1, 2, '/icons/skills/barbarian/4.png', 3);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Mace Mastery', 4, 2, 1, 3, '/icons/skills/barbarian/6.png', 4);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Howl', 4, 3, 1, 1, '/icons/skills/barbarian/8.png', 5);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Find Potion', 4, 3, 1, 3, '/icons/skills/barbarian/10.png', 6);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Leap', 4, 1, 2, 1, '/icons/skills/barbarian/12.png', 7);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Double Swing', 4, 1, 2, 3, '/icons/skills/barbarian/14.png', 8);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Pole Arm Mastery', 4, 2, 2, 1, '/icons/skills/barbarian/16.png', 9);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Throwing Mastery', 4, 2, 2, 2, '/icons/skills/barbarian/18.png', 10);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Spear Mastery', 4, 2, 2, 3, '/icons/skills/barbarian/20.png', 11);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Taunt', 4, 3, 2, 1, '/icons/skills/barbarian/22.png', 12);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Shout', 4, 3, 2, 2, '/icons/skills/barbarian/24.png', 13);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Stun', 4, 1, 3, 2, '/icons/skills/barbarian/26.png', 14);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Double Throw', 4, 1, 3, 3, '/icons/skills/barbarian/28.png', 15);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Increased Stamina', 4, 2, 3, 1, '/icons/skills/barbarian/30.png', 16);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Find Item', 4, 3, 3, 3, '/icons/skills/barbarian/32.png', 17);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Leap Attack', 4, 1, 4, 1, '/icons/skills/barbarian/34.png', 18);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Concentrate', 4, 1, 4, 2, '/icons/skills/barbarian/36.png', 19);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Iron Skin', 4, 2, 4, 3, '/icons/skills/barbarian/38.png', 20);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Battle Cry', 4, 3, 4, 1, '/icons/skills/barbarian/40.png', 21);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Frenzy', 4, 1, 5, 3, '/icons/skills/barbarian/42.png', 22);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Increased Speed', 4, 2, 5, 1, '/icons/skills/barbarian/44.png', 23);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Battle Orders', 4, 3, 5, 2, '/icons/skills/barbarian/46.png', 24);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Grim Ward', 4, 3, 5, 3, '/icons/skills/barbarian/48.png', 25);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Whirlwind', 4, 1, 6, 1, '/icons/skills/barbarian/50.png', 26);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Berserk', 4, 1, 6, 2, '/icons/skills/barbarian/52.png', 27);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Natural Resistance', 4, 2, 6, 3, '/icons/skills/barbarian/54.png', 28);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('War Cry', 4, 3, 6, 1, '/icons/skills/barbarian/56.png', 29);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Battle Command', 4, 3, 6, 2, '/icons/skills/barbarian/58.png', 30);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Raven', 5, 1, 1, 2, '/icons/skills/druid/0.png', 1);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Plague Poppy', 5, 1, 1, 3, '/icons/skills/druid/2.png', 2);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Dire Wolf', 5, 2, 1, 1, '/icons/skills/druid/20.png', 3);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Shape Shifting', 5, 2, 1, 2, '/icons/skills/druid/52.png', 4);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Firestorm', 5, 3, 1, 1, '/icons/skills/druid/32.png', 5);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Oak Sage', 5, 1, 2, 1, '/icons/skills/druid/16.png', 6);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Summon Spirit Wolf', 5, 1, 2, 2, '/icons/skills/druid/6.png', 7);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Mammoth Bear', 5, 2, 2, 3, '/icons/skills/druid/22.png', 8);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Molten Boulder', 5, 3, 2, 1, '/icons/skills/druid/34.png', 9);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Arctic Blast', 5, 3, 2, 3, '/icons/skills/druid/36.png', 10);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Cycle of Life', 5, 1, 3, 3, '/icons/skills/druid/8.png', 11);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Feral Rage', 5, 2, 3, 1, '/icons/skills/druid/54.png', 12);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Maul', 5, 2, 3, 3, '/icons/skills/druid/56.png', 13);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Eruption', 5, 3, 3, 1, '/icons/skills/druid/38.png', 14);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Cyclone Armor', 5, 3, 3, 3, '/icons/skills/druid/40.png', 15);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Heart of Wolverine', 5, 1, 4, 1, '/icons/skills/druid/10.png', 16);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Summon Fenris', 5, 1, 4, 2, '/icons/skills/druid/12.png', 17);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Rabies', 5, 2, 4, 1, '/icons/skills/druid/24.png', 18);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fire Claws', 5, 2, 4, 2, '/icons/skills/druid/26.png', 19);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Twister', 5, 3, 4, 2, '/icons/skills/druid/42.png', 20);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Vines', 5, 1, 5, 3, '/icons/skills/druid/14.png', 21);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Hunger', 5, 2, 5, 2, '/icons/skills/druid/58.png', 22);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Shock Wave', 5, 2, 5, 3, '/icons/skills/druid/28.png', 23);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Volcano', 5, 3, 5, 1, '/icons/skills/druid/44.png', 24);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Tornado', 5, 3, 5, 2, '/icons/skills/druid/46.png', 25);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Spirit of Barbs', 5, 1, 6, 1, '/icons/skills/druid/4.png', 26);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Summon Grizzly', 5, 1, 6, 2, '/icons/skills/druid/18.png', 27);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fury', 5, 2, 6, 1, '/icons/skills/druid/30.png', 28);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Armageddon', 5, 3, 6, 1, '/icons/skills/druid/50.png', 29);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Hurricane', 5, 3, 6, 2, '/icons/skills/druid/48.png', 30);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fire Trauma', 6, 1, 1, 2, '/icons/skills/assassin/0.png', 1);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Claw Mastery', 6, 2, 1, 2, '/icons/skills/assassin/20.png', 2);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Psychic Hammer', 6, 2, 1, 3, '/icons/skills/assassin/22.png', 3);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Tiger Strike', 6, 3, 1, 2, '/icons/skills/assassin/40.png', 4);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Dragon Talon', 6, 3, 1, 3, '/icons/skills/assassin/42.png', 5);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Shock Field', 6, 1, 2, 1, '/icons/skills/assassin/2.png', 6);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Blade Sentinel', 6, 1, 2, 3, '/icons/skills/assassin/4.png', 7);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Quickness', 6, 2, 2, 1, '/icons/skills/assassin/36.png', 8);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fists of Fire', 6, 3, 2, 1, '/icons/skills/assassin/44.png', 9);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Dragon Claw', 6, 3, 2, 3, '/icons/skills/assassin/46.png', 10);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Charged Bolt Sentry', 6, 1, 3, 1, '/icons/skills/assassin/6.png', 11);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Wake of Fire Sentry', 6, 1, 3, 2, '/icons/skills/assassin/8.png', 12);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Weapon Block', 6, 2, 3, 2, '/icons/skills/assassin/26.png', 13);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Cloak of Shadows', 6, 2, 3, 3, '/icons/skills/assassin/24.png', 14);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Cobra Strike', 6, 3, 3, 2, '/icons/skills/assassin/50.png', 15);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Blade Fury', 6, 1, 4, 3, '/icons/skills/assassin/10.png', 16);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Fade', 6, 2, 4, 1, '/icons/skills/assassin/30.png', 17);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Shadow Warrior', 6, 2, 4, 2, '/icons/skills/assassin/38.png', 18);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Claws of Thunder', 6, 3, 4, 1, '/icons/skills/assassin/58.png', 19);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Dragon Tail', 6, 3, 4, 3, '/icons/skills/assassin/48.png', 20);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Lightning Sentry', 6, 1, 5, 1, '/icons/skills/assassin/12.png', 21);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Inferno Sentry', 6, 1, 5, 2, '/icons/skills/assassin/14.png', 22);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Mind Blast', 6, 2, 5, 3, '/icons/skills/assassin/34.png', 23);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Blades of Ice', 6, 3, 5, 1, '/icons/skills/assassin/52.png', 24);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Dragon Flight', 6, 3, 5, 3, '/icons/skills/assassin/54.png', 25);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Death Sentry', 6, 1, 6, 1, '/icons/skills/assassin/16.png', 26);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Blade Shield', 6, 1, 6, 3, '/icons/skills/assassin/18.png', 27);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Venom', 6, 2, 6, 1, '/icons/skills/assassin/28.png', 28);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Shadow Master', 6, 2, 6, 2, '/icons/skills/assassin/32.png', 29);
INSERT INTO lod.tbl_skill (name, class_id, page, skill_row, skill_col, icon, byte_order) VALUES ('Royal Strike', 6, 3, 6, 2, '/icons/skills/assassin/56.png', 30);