INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Den of Evil', 1, 0, 1);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Sisters'' Burial Grounds', 1, 1, 2);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Tools of the Trade', 1, 2, 5);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Search for Cain', 1, 3, 3);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Forgotten Tower', 1, 4, 4);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Sisters to the Slaughter', 1, 5, 6);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Radament''s Lair', 2, 0, 1);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Horadric Staff', 2, 1, 2);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Tainted Sun', 2, 2, 3);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Arcane Sanctuary', 2, 3, 4);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Summoner', 2, 4, 5);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Seven Tombs', 2, 5, 6);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Lam Esen''s Tome', 3, 0, 4);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Khalim''s Will', 3, 1, 3);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Blade of the Old Religion', 3, 2, 2);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Golden Bird', 3, 3, 1);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Blackened Temple', 3, 4, 5);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Guardian', 3, 5, 6);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('The Fallen Angel', 4, 0, 1);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Terror''s End', 4, 1, 3);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Hell''s Forge', 4, 2, 2);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Siege on Harrogath', 5, 0, 1);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Rescue on Mount Arreat', 5, 1, 2);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Prison of Ice', 5, 2, 3);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Betrayal of Harrogath', 5, 3, 4);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Rite of Passage', 5, 4, 5);
INSERT INTO tbl_quest (name, act, position, quest_position) VALUES ('Eve of Destruction', 5, 5, 6);